In [ ]:
from sklearn.neighbors import KNeighborsClassifier

## K Nearest Neighnors alogirthm is used for both:
   ### Supervised Learning  --->>> Both Regression and Classification.
   ### Unsupervised Learning --->>> Clustering.
  
  ## This alogirthim works based on the distances. How do we calculate distance:
        ---> Eulidean Distance. sqrt ((a-c)*2 + (b-d)*2)
    ### --> Manhattan Distance. |a-c| + |b-d|

## To calculate distance kenighbors uses 3 type of alogirtm. They are :
  * Brute Force.
  * Ball Tree.
  * KD 

In [2]:
from sklearn import datasets

In [3]:
iris = datasets.load_iris()

In [4]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [5]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
iris.data

In [ ]:
knn = KNeighborsClassifier(n_neighbors=3)

In [ ]:
fitmodel = knn.fit(iris['data'],iris['target'])

In [ ]:
type(fitmodel)

In [ ]:
# Measuring the performance of model

In [ ]:
## Accuracy --- > Fraction of correfct predictions

#### NO of correctly identified items to the no of total identified items
## Percentage of correct predictions

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(iris['data'],iris['target'],test_size = 0.2,random_state = 12)

In [8]:
X_train

array([[5.1, 3.5, 1.4, 0.3],
       [5.5, 2.4, 3.7, 1. ],
       [6.3, 2.9, 5.6, 1.8],
       [5.5, 4.2, 1.4, 0.2],
       [5.8, 2.7, 5.1, 1.9],
       [5.7, 4.4, 1.5, 0.4],
       [5.6, 2.9, 3.6, 1.3],
       [5.5, 2.4, 3.8, 1.1],
       [5.8, 4. , 1.2, 0.2],
       [6. , 2.2, 4. , 1. ],
       [5.1, 2.5, 3. , 1.1],
       [5. , 3.4, 1.6, 0.4],
       [4.4, 2.9, 1.4, 0.2],
       [5.1, 3.8, 1.5, 0.3],
       [4.8, 3. , 1.4, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [5.1, 3.8, 1.6, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [6.7, 3.3, 5.7, 2.1],
       [5. , 3.4, 1.5, 0.2],
       [6.4, 2.8, 5.6, 2.2],
       [6. , 3.4, 4.5, 1.6],
       [6.9, 3.1, 4.9, 1.5],
       [6.1, 2.9, 4.7, 1.4],
       [5.3, 3.7, 1.5, 0.2],
       [6.4, 2.7, 5.3, 1.9],
       [5.8, 2.6, 4. , 1.2],
       [6.1, 3. , 4.6, 1.4],
       [6.9, 3.2, 5.7, 2.3],
       [4.9, 3.1, 1.5, 0.1],
       [5.7, 2.5, 5. , 2. ],
       [5.4, 3.9, 1.7, 0.4],
       [6.7, 3.3, 5.7, 2.5],
       [4.9, 2.5, 4.5, 1.7],
       [5.8, 2

In [9]:
X_test

array([[5. , 3.5, 1.3, 0.3],
       [6.3, 2.5, 5. , 1.9],
       [4.4, 3. , 1.3, 0.2],
       [5.7, 2.8, 4.1, 1.3],
       [6.8, 3.2, 5.9, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [6.2, 3.4, 5.4, 2.3],
       [5.1, 3.4, 1.5, 0.2],
       [7.7, 3. , 6.1, 2.3],
       [5.1, 3.3, 1.7, 0.5],
       [5.6, 3. , 4.5, 1.5],
       [5.4, 3.9, 1.3, 0.4],
       [5.4, 3.4, 1.5, 0.4],
       [5.1, 3.7, 1.5, 0.4],
       [7. , 3.2, 4.7, 1.4],
       [7.2, 3.2, 6. , 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [5.9, 3. , 4.2, 1.5],
       [4.6, 3.4, 1.4, 0.3],
       [6.3, 2.5, 4.9, 1.5],
       [4.9, 3. , 1.4, 0.2],
       [6.1, 2.8, 4. , 1.3],
       [6.2, 2.8, 4.8, 1.8],
       [6. , 2.9, 4.5, 1.5],
       [4.8, 3.4, 1.9, 0.2],
       [6.7, 3. , 5.2, 2.3],
       [6.7, 3. , 5. , 1.7],
       [5.5, 2.6, 4.4, 1.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.5, 2.3, 1.3, 0.3]])

In [10]:
knn = KNeighborsClassifier(n_neighbors=3)

In [11]:
model = knn.fit(X_train,y_train)

In [12]:
y_test

array([0, 2, 0, 1, 2, 2, 2, 0, 2, 0, 1, 0, 0, 0, 1, 2, 2, 1, 0, 1, 0, 1,
       2, 1, 0, 2, 1, 1, 0, 0])

In [13]:
y_pred = model.predict(X_test)

In [14]:
y_pred

array([0, 2, 0, 1, 2, 2, 2, 0, 2, 0, 1, 0, 0, 0, 1, 2, 2, 1, 0, 2, 0, 1,
       2, 1, 0, 2, 1, 1, 0, 0])

In [17]:
knn.score(X_test,y_test)

0.9666666666666667

In [18]:
y_pred - y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

### knn classifier is best know for its classification
## Knn algorithm is non parametric model --- > we cannot put our required parameters, It will use all the parameters given 

    *we need to import the modules first. 
    *from sklearn.model_selection import KNeighnorsClassifier.
    * Prepare the training and test data sets
    * Create the object to KNeighborsClassifier class with n_neighbors counts ---> basically optimal neighors 
    * Fit the training set to model by providing the X(Independand varaible) and y(dependad variable).
    * Now you can predict the any value with the create model.
 

In [19]:
# what is meant bby hyperparameter tunning? 


In [24]:
from sklearn.model_selection import GridSearchCV
import numpy as np

In [32]:
parms = {'n_neighbors' : np.arange(1,50)}

In [33]:
knn_new = GridSearchCV(knn,parms,cv = 5)

In [34]:
knn_new.fit(X_train,y_train)

C:\Users\saina\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                            metric='minkowski',
                                            metric_params=None, n_jobs=None,
                                            n_neighbors=3, p=2,
                                            weights='uniform'),
             iid='warn', n_jobs=None,
             param_grid={'n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [35]:
knn_new.best_score_

0.9833333333333333

In [36]:
knn_new.best_params_

{'n_neighbors': 3}