### We do have SVR and SVC --> Support vector regression and Support vector Classifier.
            ** Now lets talk about SVC.
            This SVC is used to classifiy both 
             ---> Linearly separable datasets
             ---> Non - Linearly Separable datasets
             
             ** Linearly Seperable datasets:
              Its draws a best fit line (optimal line) which separtes the two datasets.
              SVC is very special because it finds the dataset extremes, and draws a line which maxmimum margin.
              Any datapoint which crosses the marigin then we classify the datapoint as other datapoint.
             

In [5]:
## Import the modules
import pandas as pd
from sklearn.svm import SVC


C:\Users\saina\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\saina\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [6]:
data = pd.read_csv('Social_Network_Ads.csv')

In [7]:
data

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [8]:
X = data.iloc[:,2:3].values

In [9]:
X

array([[19],
       [35],
       [26],
       [27],
       [19],
       [27],
       [27],
       [32],
       [25],
       [35],
       [26],
       [26],
       [20],
       [32],
       [18],
       [29],
       [47],
       [45],
       [46],
       [48],
       [45],
       [47],
       [48],
       [45],
       [46],
       [47],
       [49],
       [47],
       [29],
       [31],
       [31],
       [27],
       [21],
       [28],
       [27],
       [35],
       [33],
       [30],
       [26],
       [27],
       [27],
       [33],
       [35],
       [30],
       [28],
       [23],
       [25],
       [27],
       [30],
       [31],
       [24],
       [18],
       [29],
       [35],
       [27],
       [24],
       [23],
       [28],
       [22],
       [32],
       [27],
       [25],
       [23],
       [32],
       [59],
       [24],
       [24],
       [23],
       [22],
       [31],
       [25],
       [24],
       [20],
       [33],
       [32],
       [34],
       [18],

In [10]:
y = data.iloc[:,-1].values

In [11]:
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test , y_train, y_test  = train_test_split(X,y,test_size = 0.2, random_state = 12)

In [16]:
SVC?

In [17]:
model = SVC(kernel='linear')

In [18]:
model

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [19]:
model.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [20]:
y_pred = model.predict(X_test)

In [21]:
y_pred

array([1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0], dtype=int64)

In [22]:
y_test

array([1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [23]:
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(model.score(X_test,y_test))

[[40  8]
 [10 22]]
              precision    recall  f1-score   support

           0       0.80      0.83      0.82        48
           1       0.73      0.69      0.71        32

    accuracy                           0.78        80
   macro avg       0.77      0.76      0.76        80
weighted avg       0.77      0.78      0.77        80

0.775


In [25]:
## Import the modules
import pandas as pd
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
data = pd.read_csv('Social_Network_Ads.csv')
X = data.iloc[:,2:3].values
y = data.iloc[:,-1].values
X_train, X_test , y_train, y_test  = train_test_split(X,y,test_size = 0.2, random_state = 12)
model2 = SVC(kernel='rbf')
model2.fit(X_train,y_train)
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(model2.score(X_test,y_test))

[[40  8]
 [10 22]]
              precision    recall  f1-score   support

           0       0.80      0.83      0.82        48
           1       0.73      0.69      0.71        32

    accuracy                           0.78        80
   macro avg       0.77      0.76      0.76        80
weighted avg       0.77      0.78      0.77        80

0.775


C:\Users\saina\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [26]:
model2

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)