In [2]:
# Artificial Neural Network

# Installing Theano
# pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git

# Installing Tensorflow
# Install Tensorflow from the website: https://www.tensorflow.org/versions/r0.12/get_started/os_setup.html

# Installing Keras
# pip install --upgrade keras

# Part 1 - Data Preprocessing

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

C:\Users\saina\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\saina\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [4]:
X_train

array([[-0.5698444 ,  1.74309049,  0.16958176, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [ 1.75486502, -0.57369368, -2.30455945, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [-0.5698444 , -0.57369368, -1.19119591, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [-0.5698444 , -0.57369368,  0.9015152 , ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-0.5698444 ,  1.74309049, -0.62420521, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [ 1.75486502, -0.57369368, -0.28401079, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [5]:
y_train

array([0, 0, 0, ..., 0, 0, 1], dtype=int64)

In [6]:
# importing the keras 
import keras

Using TensorFlow backend.


In [7]:
from keras.models import Sequential

In [8]:
from keras.layers import Dense

In [9]:
#After importing the required modules we need to create a object for sequential

In [10]:
classifier = Sequential?

In [11]:
classifier = Sequential()

In [16]:
classifier
    

In [20]:
classifier.add(Dense(input_dim = 11,output_dim = 6, kernel_initializer = 'uniform',activation = 'relu'))

C:\Users\saina\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=11, kernel_initializer="uniform", activation="relu", units=6)`
  """Entry point for launching an IPython kernel.


In [21]:
classifier

In [22]:
classifier.add(Dense(output_dim = 1, kernel_initializer = 'uniform',activation = 'sigmoid'))

C:\Users\saina\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", activation="sigmoid", units=1)`
  """Entry point for launching an IPython kernel.


In [24]:
classifier.compile(optimizer= 'adam',loss = 'binary_crossentropy',metrics= ['accuracy'])

In [29]:
classifier.fit(X_train,y_train,batch_size= 10, nb_epoch = 100)


Epoch 1/100
1010/8000 [==>...........................] - ETA: 1s - loss: 0.3361 - accuracy: 0.8634

C:\Users\saina\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


8000/8000 [==============================] - 1s 133us/step - loss: 0.3339 - accuracy: 0.8648
Epoch 2/100
8000/8000 [==============================] - 1s 127us/step - loss: 0.3348 - accuracy: 0.8615
Epoch 3/100
8000/8000 [==============================] - 1s 137us/step - loss: 0.3327 - accuracy: 0.8630
Epoch 4/100
8000/8000 [==============================] - 1s 136us/step - loss: 0.3328 - accuracy: 0.8620
Epoch 5/100
8000/8000 [==============================] - 1s 127us/step - loss: 0.3334 - accuracy: 0.8614
Epoch 6/100
8000/8000 [==============================] - 1s 128us/step - loss: 0.3327 - accuracy: 0.8609
Epoch 7/100
8000/8000 [==============================] - 1s 128us/step - loss: 0.3327 - accuracy: 0.8633
Epoch 8/100
8000/8000 [==============================] - 1s 131us/step - loss: 0.3329 - accuracy: 0.8624
Epoch 9/100
8000/8000 [==============================] - 1s 168us/step - loss: 0.3330 - accuracy: 0.8611
Epoch 10/100
8000/8000 [==============================] - 1s 174us/

8000/8000 [==============================] - 1s 138us/step - loss: 0.3304 - accuracy: 0.8620
Epoch 79/100
8000/8000 [==============================] - 1s 130us/step - loss: 0.3299 - accuracy: 0.8637
Epoch 80/100
8000/8000 [==============================] - 1s 166us/step - loss: 0.3288 - accuracy: 0.8636
Epoch 81/100
8000/8000 [==============================] - 1s 148us/step - loss: 0.3292 - accuracy: 0.8650
Epoch 82/100
8000/8000 [==============================] - 1s 137us/step - loss: 0.3293 - accuracy: 0.8654
Epoch 83/100
8000/8000 [==============================] - 1s 127us/step - loss: 0.3299 - accuracy: 0.8614
Epoch 84/100
8000/8000 [==============================] - 1s 127us/step - loss: 0.3280 - accuracy: 0.8619
Epoch 85/100
8000/8000 [==============================] - 1s 126us/step - loss: 0.3283 - accuracy: 0.8629
Epoch 86/100
8000/8000 [==============================] - 1s 141us/step - loss: 0.3291 - accuracy: 0.8641
Epoch 87/100
8000/8000 [==============================] - 1

In [30]:
y_pred = classifier.predict(X_test)

In [31]:
print(y_pred)

[[0.27412844]
 [0.17911854]
 [0.1950573 ]
 ...
 [0.15906927]
 [0.30028778]
 [0.14930385]]


In [32]:
y_test

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [33]:
y_pred = (y_pred>0.5)

In [34]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [35]:
y_pred - y_test

array([[ 0, -1,  0, ...,  0,  0,  0],
       [ 0, -1,  0, ...,  0,  0,  0],
       [ 0, -1,  0, ...,  0,  0,  0],
       ...,
       [ 0, -1,  0, ...,  0,  0,  0],
       [ 0, -1,  0, ...,  0,  0,  0],
       [ 0, -1,  0, ...,  0,  0,  0]], dtype=int64)

In [36]:
from sklearn.metrics import confusion_matrix,classification_report

In [38]:
confusion_matrix(y_test,y_pred)

array([[1490,  105],
       [ 182,  223]], dtype=int64)

In [41]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.89      0.93      0.91      1595
           1       0.68      0.55      0.61       405

    accuracy                           0.86      2000
   macro avg       0.79      0.74      0.76      2000
weighted avg       0.85      0.86      0.85      2000

